Future nextweb
tnyandoro/thenextweb-clone-responsive pull request #2
Opened 2020-09-16 08:08 UTC by tnyandoro

Please review my work for responsive design on The Next Web clone. The site was done in html, css flex, css grid and some media queries to make it responsive

2020-09-16 10:17 UTC, arslanbisharat requested changes
### Request changes
I can see you worked hard on this project but I am sorry to inform you that I cannot Approve this project because it is not completed yet.😟
_It's okay. We are here to learn. Don't get discouraged. Work more hard._
**Please have a look at the suggestions to get more understanding. 👀**
- [ ] Make your PR more Descriptive by giving more information about your project. 

- [ ] Please resolve all validation errors. You can find those by posting link of index.html into [this link](https://validator.w3.org/) 
![validation](https://user-images.githubusercontent.com/58504655/93321057-397d0c00-f82b-11ea-8ac6-ec7fd7c7b930.jpg)

- [ ] Remove this bug on small size objects. 
![chrome-capture (9)](https://user-images.githubusercontent.com/58504655/93321540-b7411780-f82b-11ea-982c-03ccd77b20c5.jpg)

- [x]  Please remove this space
![chrome-capture (10)](https://user-images.githubusercontent.com/58504655/93321703-ebb4d380-f82b-11ea-9bb4-83acb98116f0.jpg)

- [x] why there is a logo on large screen
![chrome-capture (11)](https://user-images.githubusercontent.com/58504655/93321964-3a626d80-f82c-11ea-9956-595b911e2477.jpg)

- [x] logo and text is not align as it should be
![chrome-capture (12)](https://user-images.githubusercontent.com/58504655/93322077-5c5bf000-f82c-11ea-87e4-89599945d69e.jpg)

- [x] extra space is present here please remove it
![chrome-capture (13)](https://user-images.githubusercontent.com/58504655/93322443-c1afe100-f82c-11ea-87ab-5b8a6f5c4d6b.jpg)

- [x] Remove all comments that are not necessary 

- [ ]  Align logo on your footer correctly. 
![chrome-capture (8)](https://user-images.githubusercontent.com/58504655/93320935-16525c80-f82b-11ea-9e69-dcc7fac8c9e7.jpg)



[Optional] You have deployed your app on netlify. That's amazing but try to use Github resources like [this](https://raw.githack.com/).  


**Please make the changes and request re-review for the given project**
Stay safe😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +  <!-- navigation -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +    <!--main navigation for all screen -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +  <!-- this is the fourth section with grid -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +    <!-- section for single item with flex -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- second div with flex direction -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +    <!-- section for single item with flex -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- Main pic div -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- second div with flex direction -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- UL elements -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +     <!-- section for single item with flex -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- second div with flex direction -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +    <!-- section for single item with flex -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- second div with flex direction -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +    <!-- section for single item with flex -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- Main pic div -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- second div with flex direction -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <div class="ul-news-elements">
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +    <!-- section for single item with flex -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +    <!-- section for single item with flex -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- Main pic div -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- second div with flex direction -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- UL elements -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +    <!-- section for single item with flex -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- Main pic div -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +      <!-- second div with flex direction -->
remove comments that are not necessary

2020-09-16 10:17 UTC, arslanbisharat commented on index.html
> +    <!-- section for single item with flex -->
remove comments that are not necessary

2020-09-16 21:12 UTC, tnyandoro commented
Changes have been made please review the work

2020-09-16 22:41 UTC, teekaytech reviewed
# Status:  Changes required :recycle: 

**Hi @tnyandoro, you've really done a lot in this project and I'm happy to tell you that you are almost there :muscle:**

**However, some changes are required which you will have to fix, after which you can request for another review:**

- [ ] This bug still persists on small screen sizes (space to the right). Kindly fix it.
![400](https://user-images.githubusercontent.com/26856491/93399275-268f2980-f875-11ea-8ea2-66b93d4da6a8.png)


- [ ] Your navigation bar still presents on small screen sizes. 
![300](https://user-images.githubusercontent.com/26856491/93398879-440fc380-f874-11ea-9110-3422b862cc61.png)

See the image below from the main website and compare it with yours:
![200](https://user-images.githubusercontent.com/26856491/93398916-5b4eb100-f874-11ea-9e86-d5cddb287de7.png)

* * *
Kindly make those changes then request another review.

**Taofeek Olalere**
*__Slack (@taofeekolalere) or GitHub (@teekaytech).__*

**Happy coding. :man_technologist:**

2020-09-17 09:15 UTC, tnyandoro commented
The navigation bug has been resolved and the extra space on the page has been removed. All the change requests have been resolved.
Kindly review

2020-09-17 09:36 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-17 09:44 UTC, umairarshadbutt approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://zen-feynman-250612.netlify.app/) shows a good understanding and usage of Bootstrap. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @tnyandoro! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-19 18:59 UTC, tnyandoro commented
Merge

2020-09-19 19:12 UTC, merged